### ISSUE TITLE
fix: Shui_Ma (1)

### ISSUE THREAD

**Issue by FireEvenstar** [PurpleMonkeyMC/Documentation#7]
### 您的游戏用户名

Shui_Ma

### 问题类目

创意(CREATIVE)

### 问题简述

提高变量数量

### 问题复现

变量上限15个之后无法创建

### 预期结果

变量数量15后 无法创建

### 其他补充

希望提高变量上限  最好无限制

**Comment by CarmJos** [comment]
![image](https://github.com/user-attachments/assets/f37cdf88-9dcd-490b-90be-fa1a44c5914e)
新版本已修复。
