### ISSUE TITLE
feat: Shui_Ma (some advice)

### ISSUE THREAD

**Issue by FireEvenstar** [PurpleMonkeyMC/Documentation#8]
### 您的游戏用户名

Shui_Ma

### 功能类目

游戏功能开发

### 功能简述

创意功能

### 需求来源

1. 创意工坊编辑地图显示好友头像可以直接点击邀请
2. 水嫩嫩吗: 12-26 20:52:16
2. 创意工坊图（可以是质量好的，例如点赞超过...）可以统计玩家pb与现在的对比（与练习/评级图相似）
3.显示个人页面的材质包差错？
4.recommand指令修复

### 功能参考

无

### 其他补充

无

**Comment by CarmJos** [comment]
请拆分这些问题
